### ISSUE TITLE
Problems with startFromZero property.

### ISSUE THREAD

**Issue by claudio-rosati** [HanSolo/Medusa#105]
Gauge.setStartFromZero:1379 and Gauge.startFromZeroProperty:1389 set the current value to a new one depending on the new startFromZero property value.

This pose a serious problem (`Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: Gauge.value : A bound value cannot be set`) if the value property is unidirectionally bounded.

Can these two statements be removed? (I don't understand the advantage of keeping them)

**Comment by HanSolo** [comment]
Fix with commit 4f5bd77e265399c613060cb8f3d35eb707f008ba
