### ISSUE TITLE
Different value text size for similar gauges

### ISSUE THREAD

**Issue by DJViking** [HanSolo/Medusa#118]
Having problems with text size being different among multiple gauges of same size.
Whether it displays value -10.00, 10.00, or 0.00 text size should be the same.
Having several gauges in one view it does not look good having the text values in different sizes.

On some instances I noticed on two gauges having the same number of digits in the value, but each with slightly different text size.

```
gauge = GaugeBuilder.create()
         .skinType(SkinType.DASHBOARD)
         .decimals(2)
         .build();
```

Tried setting customFont, but it has no effect on the text.
```
gauge.setCustomFontEnabled(true);
gauge.setCustomFont(Fonts.latoBold(8));
```

Attaching some screenshots that display this problem.
![screenshot_20170426_113834](https://cloud.githubusercontent.com/assets/3070076/25431076/5dc32ed2-2a7f-11e7-8a11-3fec1c80208e.png)
![screenshot_20170424_090323](https://cloud.githubusercontent.com/assets/3070076/25431082/603b7840-2a7f-11e7-9843-3c14d92b566a.png)
![screenshot_20170426_123949](https://cloud.githubusercontent.com/assets/3070076/25431084/62aa9d90-2a7f-11e7-9dc6-2c30aeddb30b.png)

**Comment by HanSolo** [comment]
The problem is that if the value text become wider than a certain limit I resize it to make sure it will be shown. I could implement something like adjusting the value font size to the max width of the maxValue. This might work better.

**Comment by claudio-rosati** [comment]
Is not possible to provide a formatter that wil format always number with a certain number of digits before and after the decimal points?

**Comment by HanSolo** [comment]
That might also be an option...

**Comment by HanSolo** [comment]
Will add a decimalFormat property that will be used in the future to format the numbers. Might take some time to adjust all skins but it will come... :)

**Comment by HanSolo** [comment]
Found a better solution that works also for negative values so stay tuned... :)

**Comment by HanSolo** [comment]
The latest commit contains the latest changes. So if you have time feel free to test the new number formatting. I think it should work now the way you need it. Thx for the heads up 👍🏻

**Comment by DJViking** [comment]
I have updated the version of Medusa to 7.9, and it looks a little better, but I still notice differences in size among my gauges. Is there anything additional I need to in my code?

Two gauges with the same number of digits was displayed with slightly different size.
![spectacle j21608](https://cloud.githubusercontent.com/assets/3070076/25607912/0ad11236-2f19-11e7-90e9-a24e3c940c16.png)
