### ISSUE TITLE
Current, Average, Min and Max as separate "first class gauge" elements

### ISSUE THREAD

**Issue by WolfgangFahl** [HanSolo/Medusa#121]
The Temperature Example shows a nice display of values with min max, current and old value. It has 8 display items in total which are aranged around each other with different sizes.

Instead of having this complex 8 part arrangement I'd prefere to be able to simply arrange a few of the items below each other with the same size.

E.g:
Current:
Min: 
Avg:
Max:

How could I achieve this? I have looked at the source code but I couldn't find the "subgauges" to be handled like this.

**Comment by HanSolo** [comment]
Which temperature example are you referring to? Could you provide a screenshot?

**Comment by HanSolo** [comment]
If you are referring to the LcdSkin there is no way to re-arrange the parameters in the skin. To achieve this you have to create your own skin that can look whatever you like it to be.
So you simply create a skin that makes use of those properties from the Gauge class. Each skin in Medusa is just another visualization of the Gauge model and uses only the properties that are needed for this specific visualization.

**Comment by WolfgangFahl** [comment]
Thx for the swift answer I was hoping to be able to reuse skin elements. I'll get back with screenshots later

**Comment by HanSolo** [comment]
Well if you attach a screenshot how it should look like and it makes sense there is no reason not to create another Lcd like skin. It just have to make sense for more than one person ;)

**Comment by WolfgangFahl** [comment]
I tried to create an example and get screen shots for it but miserably failed. 
I tried a variant of the LCDField class https://github.com/BITPlan/can4eve/blob/master/obdii/src/main/java/eu/hansolo/LcdField.java fiddling with the size factors and tried creating a Skin for this see https://github.com/BITPlan/can4eve/blob/master/obdii/src/main/java/com/bitplan/obdii/javafx/LCDPane.java. 

 
The test does something
> @Test
>   public void testLCDPane() throws Exception {
>     WaitableApp.toolkitInit();
>     LCDPane lcdPane=new LCDPane(2,2,200,30,LcdFont.LCD,"r1c1","r1c2","r2c1","r2c2");
>     SampleApp.createAndShow("LCDPane", lcdPane, SHOW_TIME*4);
>   }

The result is not even close to what I would like to get since I don't know how the actual redraw with painting the gradients needs to be activated.

<img width="497" alt="grafik" src="https://user-images.githubusercontent.com/1336221/27925165-163039b0-6284-11e7-8e78-12928fe3d9dc.png">

**Comment by HanSolo** [comment]
So what about switching the lcd off in the gauge and use 4 lcd gauges for the values you need. So you don't need a new control, just combine existing ones.
You could also create a drawing of your ideas...does not have to be code...just need aketch of your idea.

**Comment by WolfgangFahl** [comment]
Thx for getting back. Yes I only want the LCD gauge from main example. I simply could/can  not find it in the code of medusa. 

In the meantime I got as far as:
<img width="946" alt="grafik" src="https://user-images.githubusercontent.com/1336221/27943667-6eb5e0dc-62e1-11e7-8074-fd94f259fb4c.png">
 
By simplifying https://github.com/BITPlan/can4eve/blob/master/obdii/src/main/java/eu/hansolo/LcdField.java

and using SkinBase in 
https://github.com/BITPlan/can4eve/blob/master/obdii/src/main/java/com/bitplan/obdii/javafx/LCDPane.java

The code now looks much cleaner and I start understanding what is going on.
Thank you for your offer to go by a drawing of my ideas.
![grafik](https://user-images.githubusercontent.com/1336221/27943727-d1519290-62e1-11e7-8ec7-9e41b481a41c.png)

![grafik](https://user-images.githubusercontent.com/1336221/27943731-d7534882-62e1-11e7-8328-59cafcbc5480.png)

with some labels will suffice.

**Comment by WolfgangFahl** [comment]
The newest state of affairs is:
<img width="965" alt="grafik" src="https://user-images.githubusercontent.com/1336221/27944485-7d821f3a-62e7-11e7-9314-5d5774f005a5.png">

So it looks like the standard font robotoMedium does not show on my Mac.  What is the font used in the example Pressure Gauge? 
<img width="128" alt="grafik" src="https://user-images.githubusercontent.com/1336221/27944515-a78eb266-62e7-11e7-99ce-bf5ea63739cd.png">

**Comment by WolfgangFahl** [comment]
The latest result is looking the way I would like it to look:
<img width="1144" alt="grafik" src="https://user-images.githubusercontent.com/1336221/27945084-3c6381c0-62eb-11e7-82ce-4a8a27f853e4.png">

I am not sure whether the layoutChildren part is correct:

 ```
@Override
    public void layoutChildren(double contentX, double contentY,
        double contentWidth, double contentHeight) {
      super.layoutChildren(contentX, contentY, contentWidth, contentHeight);
      LcdField lcdField = this.getSkinnable();
      Label lcdText = lcdField.getLcdText();
      // lcdText.setTranslateX(-lcdField.getLcd().getWidth());
      lcdText.setTranslateX(-contentWidth / 2);
    }
```

I'd love to see that something like:
https://github.com/BITPlan/can4eve/blob/master/obdii/src/main/java/eu/hansolo/LcdField.java

is incorporated into Medusa at least as an example on how to create own Skins. For me this took a few hours although the result doesn't look too complicated.

**Comment by WolfgangFahl** [comment]
I have given up this approach and I am using "standard" controls. From my point of view this issue may be closed. Still I'd suggest to refactor the code to make it more modular and understandable and allow the reuse of "subcomponents".

**Comment by HanSolo** [comment]
Well the whole idea is to create your own skin for the gauge class. That skin can contain whatever you like, means if you need a specific visualization, just create a skin for it.
It's not the idea to have parts of skins be reusable like subgauges etc.
