### ISSUE TITLE
Gauge LINEAR Tick Marks visibility not affected

### ISSUE THREAD

**Issue by DJViking** [HanSolo/Medusa#136]
Having a Gauge with SkinType LINEAR I am unable to set TickMarks invisible.
gauge.setMajorTickMarksVisible(false);
gauge.setMinorTickMarksVisible(false);
gauge.setMediumTickMarksVisible(false);

![spectacle j30532](https://user-images.githubusercontent.com/3070076/30312350-6c2fb3c8-9799-11e7-9f67-0c6ea3a9902a.png)

**Comment by HanSolo** [comment]
Fixed with commit cd4423a3fef22798c41d5f6
