### ISSUE TITLE
Display angle?

### ISSUE THREAD

**Issue by piegamesde** [HanSolo/Medusa#137]
I need to display an angle, but not with a needle, but with two needles enclosing that angle. Is this possible to do with this library? I also thought about overlaying two gauges but I wanted to ask if there are any official solutions first.

By the way: I googled my problem, found your blog article, plugged in the code and it worked _marvelously_. This is rare in the JavaFX world, so thanks for that! This library definitely needs more attention.

**Comment by HanSolo** [comment]
Well it is not possible at the moment but I can make it possible :)
It would be very helpful to have a drawing, photo or screenshot of the gauge you are looking for. Could you provide something like that?

**Comment by piegamesde** [comment]
I want the user to input an angle for the [field of view](https://www.google.de/search?q=field+of+view&tbm=isch) of a camera (<180°). Anything that represents this visually in a clear way and does not clash with my compass above it is fine. Here my compass for reference:

```
		Gauge gauge = GaugeBuilder.create()
				.minValue(0)
				.maxValue(359)
				.startAngle(180)
				.angleRange(360)
				.autoScale(false)
				.customTickLabelsEnabled(true)
				.customTickLabels("N", "", "", "", "", "", "", "", "",
						"E", "", "", "", "", "", "", "", "",
						"S", "", "", "", "", "", "", "", "",
						"W", "", "", "", "", "", "", "", "")
				.customTickLabelFontSize(96)
				.minorTickMarksVisible(false)
				.mediumTickMarksVisible(false)
				.majorTickMarksVisible(false)
				.valueVisible(false)
				.needleType(NeedleType.BIG)
				.needleShape(NeedleShape.ANGLED)
				.knobType(KnobType.FLAT)
				.knobColor(Gauge.DARK_COLOR)
				.borderPaint(Gauge.DARK_COLOR)
				.animated(false)
				.animationDuration(0)
				.needleBehavior(NeedleBehavior.STANDARD)
				.build();
```

**Comment by HanSolo** [comment]
But should the field of view also point into a specific direction? So you might also think about using a section which you could show in the compass for example...

**Comment by piegamesde** [comment]
At the moment the compass shows the rotation of the camera and the field of view shows its horizontal view angle. But having both in one is absolutely a great idea I didn't think of previously. If not, I don't really care about the direction of the angle.

I'm not really far into the API with areas, sections and such but it is worth a try. Do sections use properties too or will I have to use listeners here?
