### ISSUE TITLE
SlimClockSkin uses default Locale in DateTimeFormatter

### ISSUE THREAD

**Issue by kosmelju** [HanSolo/Medusa#138]
There is day of the week displayed in default system locale when using SlimClockSkin and setting dateVisible(true). Probably DateTimeFormatter.ofPattern(String pattern, Locale locale) with user defined clock's Locale should be used instead of DateTimeFormatter.ofPattern(String pattern) on line 46 in SlimClockSkin.java (private static final DateTimeFormatter  DATE_TEXT_FORMATTER = DateTimeFormatter.ofPattern("cccc");). It would be also nice to be able to show/hide "day" and "date" separately.

**Comment by HanSolo** [comment]
Thanx for the report...fixed with commit a8282dbd7c3882087211a614c366437fea357a4b :)

**Comment by kosmelju** [comment]
thank you very much!
