### ISSUE TITLE
Skins are missing initial width/height change

### ISSUE THREAD

**Issue by protogenes** [HanSolo/Medusa#145]
During skin construction `registerListeners()` is called last, but width and height of the control change during `initGraphics()` when adding the children. This results in wrong layout of the skin when no further layout change happens.

using: Oracle VM 1.8.172 on Windows
![gauge-error](https://user-images.githubusercontent.com/2518035/40003734-5ba252ca-5794-11e8-8fcc-471e68b8ec66.png)

**Comment by HanSolo** [comment]
Can you provide a code snippet that reproduces the issue please?

**Comment by HanSolo** [comment]
Ok...with your code I see the problem and will take a look at it. I guess you know it but nevertheless it is not a good idea to add/remove nodes to the scene graph after it has been initialized. You could simply avoid this problem by adding the gauge before the stage will be shown e.g. Group group = new Group(gauge);

**Comment by HanSolo** [comment]
Where did you see that effect originally? In SceneBuilder?

**Comment by protogenes** [comment]
This happens in the gui builder part of our application, which is not based on SceneBuilder.
I know there are performance considerations when changing an initialised scene graph, but modifications are dictated by the dynamic nature of gui builders.
For now I removed the listener on `layoutBounds` and wait for the layout pass to set `needsLayout` to false instead.

**Comment by HanSolo** [comment]
Should be fixed with last commit (7f21691e1e0d6f23938144c744a96e52c6ab)
