### ISSUE TITLE
Unit text under max value in TILE_TEXT_KPI

### ISSUE THREAD

**Issue by DJViking** [HanSolo/Medusa#147]
The unit text is placed under the max value when using SkinType.TILE_TEXT_KPI
![screenshot_20180613_211358](https://user-images.githubusercontent.com/3070076/41372892-e8957a46-6f4e-11e8-8df8-f46828bc1e7b.png)

**Comment by HanSolo** [comment]
Fixed with commit #2dd1b293a17a0d6164da1956ea41232afbf5fae5
