### ISSUE TITLE
Turn off shadow text on Gauge with SkinType.DIGITAL

### ISSUE THREAD

**Issue by DJViking** [HanSolo/Medusa#148]
There is shadow text under title, subtitle, unit and value on Gauge SkinType.DIGITAL
Is this intended feature of this skin or a bug?

![screenshot_20180613_202832](https://user-images.githubusercontent.com/3070076/41375705-2d4aa7bc-6f57-11e8-98c7-6ba4afee9570.png)

I managed to remove the shadow text from the textValue by removing 

    backgroundCtx.fillText(new String(bkgTitleChrs), center, size * 0.35, size * 0.55);
    backgroundCtx.fillText(new String(bkgSubTitleChrs), center, size * 0.66);
    backgroundCtx.fillText(new String(bkgUnitChrs), center, size * 0.88);
    valueBkgText.setText(valueBkg.toString());

![screenshot_20180613_222951](https://user-images.githubusercontent.com/3070076/41376380-5f58c1ce-6f59-11e8-82e2-9b8120e88a48.png)

I didn't like the shadow text. Trying to mimic the real thing digital displays of old.
Perhaps have a property to allow turning off the shadow text.

Just to point out: I have two monitors. This shadow text is not visible on the older 1080p monitor, but shows clearly on my newer 1440p monitor.

**Comment by HanSolo** [comment]
Fixed with commit #2a8be2aa603cfd3781b538c0a995. Now you can make use of shadowsEnabled property to switch of the background.

**Comment by DJViking** [comment]
Great thanks
