### ISSUE TITLE
Bug in FXML

### ISSUE THREAD

**Issue by aamm188** [HanSolo/Medusa#149]
When I drag "Gauge" with other control by Scene Builder and then compile my program , my Stage don't load and in console show Errors.

**Comment by HanSolo** [comment]
It might be good to have the error messages and some piece of code to reproduce it.

**Comment by aamm188** [comment]
I tested your controls withe another  controls in Scenebuilder 2 again   and works Excellent. It's probably my Gloun  SceneBuilder  has a problem. thank's a lot
Mr HanSolo 
I'm looking for a Gauge that has a limiting arc  like first Gauge in Your Controls image, but I could not find that control among the controls and I  could not set Gauge or FGauge  withe Limitations Arc.(can you help me)
