### ISSUE TITLE
Issue with AmpSkin

### ISSUE THREAD

**Issue by hermann-59** [HanSolo/Medusa#157]
Is there a way to remove the title area when using the AmpSkin. I don't need it and it only wasts space.

Thanks in advance
Hermann

**Comment by DJViking** [comment]
We have the same need. It takes up to much space when there is no title set. Would be beneficial to remove the entire area surrounding the Amp.
![screenshot_20190125_170749](https://user-images.githubusercontent.com/3070076/51757503-d1ad0700-20c3-11e9-9f49-9848df07dac3.png)

Like this:
![screenshot_20190125_170749_2](https://user-images.githubusercontent.com/3070076/51757581-0d47d100-20c4-11e9-8199-ac25b42b8bbc.png)

**Comment by HanSolo** [comment]
Added a PlainAmpSkin to the library which is part of release 8.2
<img width="620" alt="plainampskin" src="https://user-images.githubusercontent.com/62843/52139680-1a7b3780-2651-11e9-89f0-bdd8c8375565.png">

**Comment by DJViking** [comment]
Thanks

**Comment by hermann-59** [comment]
![lcd-gauge](https://user-images.githubusercontent.com/47034192/52154214-35fc3780-267d-11e9-9bf1-ebfd71216d41.jpg)
Thats how the new skin looks like. Two questions: How can I avoid the emtpyt space around the gauge? And it there a way (similar to LCD skin) to present some test inside the gauge?

**Comment by hermann-59** [comment]
Sorry. test -> text
