### ISSUE TITLE
LCD-Skin does not display title

### ISSUE THREAD

**Issue by hermann-59** [HanSolo/Medusa#158]
I created a gauge with LCD-Skin. Subtitle gets displayed, title not. The trace shows the correct title. Whats wrong with my code?

Thanks a lot in advance
Hermann

Here's the code fragment:
        
```
GaugeBuilder builder = GaugeBuilder.create().skinType(Gauge.SkinType.LCD)
                .decimals(defaults.getDecimals())
                .minValue(defaults.getMin())
                .maxValue(defaults.getMax())
                .unit(defaults.getUnit().getUnit())
                .title(title)
                .subTitle(subtitle)
                .barColor(Color.rgb(129, 199, 132))
                .animated(true)
                .averagingEnabled(true)
                .averageVisible(true)
                .averagingPeriod(600)
                .barBackgroundColor(Color.rgb(39, 44, 50));
        Gauge gauge = builder.build();
        gauge.setValue(0.0);

        String t = gauge.getTitle();
        System.out.println("gauge title is '" + t + "'");
```

**Comment by hermann-59** [comment]
![lcd-gauge](https://user-images.githubusercontent.com/47034192/52131389-f7df2380-263c-11e9-9c9c-c7dd8772f0cb.jpg)
title was set to "Strom", Subtitle was set to "L1"

**Comment by HanSolo** [comment]
Your code is correct, there was a problem in the LCD Skin which is now fixed, please use the latest code from github to solve your problem.

**Comment by hermann-59** [comment]
![lcd-gauge](https://user-images.githubusercontent.com/47034192/52134881-e3068e00-2644-11e9-9e82-1f0c6f8a2433.jpg)

**Comment by hermann-59** [comment]
Great. It works. Thanks a lot.
