### ISSUE TITLE
SpaceX issue on Android and iOS

### ISSUE THREAD

**Issue by jperedadnr** [HanSolo/Medusa#16]
Running a gauge with `SpaceXSkin` works fine on Desktop but on Android and iOS the bars are wrong.

After some debugging, it turns out the threshold doesn't get the passed value (25000), but keeps the one it gets in the init() pass (100 due to maxValue). 

When `fireUpdateEvent(RECALC_EVENT)` in `Gauge.setMaxValue()` is triggered after a first pass (initial value 100), on desktop the max value is set immediately (30000), before the call to `setTheshold()` is made. 

But on mobile, the call to `setThreshold()` happens _before_ this second call to set the maximum value, and that's why the threshold value gets clamped.

As a quick check, setting the threshold again before running the animation fixes the problem.

**Comment by HanSolo** [comment]
Fixed
