### ISSUE TITLE
Only clock widget imported to scene builder 2.0. Please help me to import fGauge and guage

### ISSUE THREAD

**Issue by Iamjustalearner** [HanSolo/Medusa#165]
I am only able to import clock, please help me to import gauge and fgauge to import in to my scene builder 2.0

![image](https://user-images.githubusercontent.com/47646418/52820941-6c04d700-30d3-11e9-8921-a0ad8c1366f8.png)

this is my scene builder version
![image](https://user-images.githubusercontent.com/47646418/52820987-876fe200-30d3-11e9-875f-8ccf73e6257f.png)

**Comment by Adyel** [comment]
@Iamjustalearner  That scene builder is 4 years old. [Update](https://gluonhq.com/products/scene-builder/) to latest version and try maybe?

**Comment by HanSolo** [comment]
Medusa 8.3 works without a problem in SceneBuilder 8.5.0
