### ISSUE TITLE
SpaceX skin visual glitches

### ISSUE THREAD

**Issue by quigonjohnn** [HanSolo/Medusa#168]
When using the SpaceX skin, certain combinations of min, threshold and max values cause the gauge to lose its shape and grow beyond its bounds. 

![head temp](https://user-images.githubusercontent.com/6594863/55937573-9a8ad280-5c7c-11e9-8125-58b8257a7bbd.png)

min: 0
threshold: 80
max: 150

**Comment by HanSolo** [comment]
Could you provide a short snippet that shows the effect please?

**Comment by quigonjohnn** [comment]
This is how I made this one, but using the same values in scene builder leads to the same result

        GaugeBuilder builder = GaugeBuilder.create().skinType(Gauge.SkinType.SPACE_X);

        Gauge gauge = builder.minValue(0).maxValue(150).unit("\u2103").valueVisible(true).build();
        gauge.setTitleColor(Color.BLACK);
        gauge.setBarBackgroundColor(Color.rgb(217, 217, 217));
        gauge.setValueColor(Color.BLACK);
        gauge.setUnitColor(Color.BLACK);
        gauge.setAnimated(true);
        gauge.setThreshold(80);

**Comment by HanSolo** [comment]
Should hopefully be fixed with commit: #1321e4925dcde659028d4b296e49e316494c114c
