### ISSUE TITLE
MaxValue rounded every time when it sets over 100 and wrong under 100.

### ISSUE THREAD

**Issue by milosic5** [HanSolo/Medusa#177]
Hi there,
I have problem with maxValue() and value() in this source code:

Gauge g = GaugeBuilder.create().
                skinType(Gauge.SkinType.DASHBOARD).
                maxValue(15).
                value(15).
                maxWidth(300).
                maxHeight(200).
                unit("%").
                build();

it rounds maxValue to 16 and shows it on screen. Also when I want to set maxValue over 100 it rounds it every time, for example if you set 860 for maxValue it rounds it to 900 ! 
I think this is big problem and hope you can fix it.

![second](https://user-images.githubusercontent.com/10159988/65960044-d2b4e600-e453-11e9-96fa-5a62b0c292b1.png)
![first](https://user-images.githubusercontent.com/10159988/65960045-d2b4e600-e453-11e9-81a0-006ed15b61c6.png)

**Comment by HanSolo** [comment]
Hmm...interesting, I use exactly your code:
```
gauge = GaugeBuilder.create()\
                    .skinType(Gauge.SkinType.DASHBOARD)\
                    .maxValue(15)\
                    .value(15)\
                    .maxWidth(300)\
                    .maxHeight(200)\
                    .unit("%")\
                    .build();
```

and the result looks as follows:
<img width="221" alt="Test 2019-10-01 14-08-46" src="https://user-images.githubusercontent.com/62843/65960673-460b2780-e455-11e9-9e9b-e6a6229bdaff.png">
This is how it should look like right?
This was tested on the latest release 11.2

**Comment by milosic5** [comment]
Everything is ok when I put autoScale to false.

**Comment by HanSolo** [comment]
Well...that's what autoscale is for :)
