### ISSUE TITLE
Change sections, areas colors for valuse below 0.

### ISSUE THREAD

**Issue by milosic5** [HanSolo/Medusa#179]
Hi there,
let's say that I have Vertical skin and minValue= -100 and maxValue= 100. When I want to add Section from 0 to -30 and add color for that, it does not make any changes. It is also for areas which is from 0 to -50 for this example. It is same for DASHBOARD and DIGITAL skins. Everything below zero does not work for sections and areas.

![digital_skin_settings](https://user-images.githubusercontent.com/10159988/66897696-cefa9500-eff7-11e9-9e9f-80eed2d3ea0e.png)

![vertical_skin_settings](https://user-images.githubusercontent.com/10159988/66897498-6ad7d100-eff7-11e9-8d00-2d33d6f3b0d7.png)

**Comment by HanSolo** [comment]
Hmm...sounds like a bug, will take a look at that, thx for the hint

**Comment by HanSolo** [comment]
Just as an info, you should always set min/max value before you set the sections. Will try to fix it today.

**Comment by HanSolo** [comment]
Oh and you have to set the sections not from 0 to -30 but from -30 to 0.
So the sectionStart must be smaller than the sectionStop.

**Comment by milosic5** [comment]
Thanks, problem solved.
