### ISSUE TITLE
Displayed Value is too big when 2 decimals is enabled

### ISSUE THREAD

**Issue by androuino** [HanSolo/Medusa#181]
Hi, is there a way I can lower down the font size of the value? Seems like there's no option to change that in the current version of the library as of now. Thank you.

P.S. This is the reference image of what I am talking about.

![Screenshot_2019-11-14_17-22-27](https://user-images.githubusercontent.com/14807340/68839179-7eb04900-0703-11ea-81ad-23a45b17b3aa.png)

Thanks, keep up the good work guys.

**Comment by HanSolo** [comment]
the reason for this is that this skin was not meant to be used with decimals. I will try to fix it asap.

**Comment by androuino** [comment]
Thanks for the immediate response. I didn't know that it was not meant to have a decimals, looks like it wasn't written on the manual or it was at least documented. Anyways I will wait for the new update of the library. Thank you very much.

**Comment by HanSolo** [comment]
fixed with commit: 45ef97276b591ab4a32f44db96c9814f2ae8f92c

**Comment by androuino** [comment]
Great! Thanks.
