### ISSUE TITLE
Duplicate JavaFX dependencies

### ISSUE THREAD

**Issue by DJViking** [HanSolo/Medusa#182]
This library causes Gradle to fetch both the Linux and Mac dependencies for JavaFX.
It also happens on Windows: See https://github.com/openjfx/javafx-gradle-plugin/issues/65
Though this project also uses the javafxplugin.

**Comment by HanSolo** [comment]
Should be fixed with commit: 02d560d8c412da82efa1c5625390a0d7ca1f5b8a
