### ISSUE TITLE
SIMPLE_SECTION broken in 11.3

### ISSUE THREAD

**Issue by dubbadhar** [HanSolo/Medusa#187]
When using 11.2, a `SIMPLE_SECTION` gauge looks like this 

![image](https://user-images.githubusercontent.com/25760501/79039555-954dc400-7bff-11ea-98d4-1ba0ce3fcaa5.png)

but when using 11.3, this happens :

![image](https://user-images.githubusercontent.com/25760501/79039595-e1006d80-7bff-11ea-9a8f-737f87898f80.png)

There is a part of the gauge, which is black in colour, which is not expected

Code Snippet :
```
Gauge memoryGauge = new Gauge();
memoryGauge.setSkinType(Gauge.SkinType.SIMPLE_SECTION);
memoryGauge.setTitleColor(Color.WHITE);
memoryGauge.setTitle("MEM");
memoryGauge.setValue(0);
memoryGauge.setValueColor(Color.WHITE);
memoryGauge.setUnitColor(Color.WHITE);
memoryGauge.setSections(new Section(0,65,Color.GREEN), new Section(65.01,75,Color.ORANGE), new Section(75.01,100,Color.RED));
memoryGauge.setUnit("%");
memoryGauge.setCache(true);
memoryGauge.setCacheHint(CacheHint.SPEED);
```
Im using Liberica JDK 14, with prebundled JavaFX 14

**Comment by HanSolo** [comment]
Fixed with commit 72ebef3da55a660c1d068822fe6d87b6f2b2d667
