### ISSUE TITLE
Impossible to have multiple gauges blinking

### ISSUE THREAD

**Issue by KingGax** [HanSolo/Medusa#188]
[multiple blinking-gauges.zip](https://github.com/HanSolo/Medusa/files/4523141/multiple.blinking-gauges.zip)

Only the first gauge to have blinking turned on seems to be able to blink. The others will just have LED on or off depending on what you set ledOn to.

**Comment by HanSolo** [comment]
Found and fixed with commit 4cbb1f0e4f2815e6f6909ce5b812c69daaea1ecd
