### ISSUE TITLE
Resizing the "Level" Skin to fillout y-Axis while maintaining the size of the x-Axis

### ISSUE THREAD

**Issue by Pureandy** [HanSolo/Medusa#190]
Hello HanSolo,

I am working with your Medusa Lib for about 4 Months now, and I really like it. :)
I have a Question about the options to resize the Gauges in only one direction. Is that possible?
For what I saw so far it does seem like it, that all Gauges stay in shape of a square.

**Comment by HanSolo** [comment]
Nope at the moment that is not possible with the provided skins. However it might be possible to create a custom skin that has a different behavior.
