### ISSUE TITLE
Skintype with "shadow" gradient inside of the Gauge

### ISSUE THREAD

**Issue by Pureandy** [HanSolo/Medusa#191]
Hello HanSolo,

In the Screenshot of all Skintypes of Medusa is one, that I can't find:
![Skintype](https://user-images.githubusercontent.com/6490663/81661524-8778a200-943c-11ea-86e6-1f4a020484ae.png)

Is this a normal skin and if not how can I, when creating a custom skin, create this shadow effect inside of the Gauge?

Thanks in advance

**Comment by HanSolo** [comment]
That is a so called framed gauge. The idea behind the FGauge was to provide different frames where you can add a gauge control e.g. for car dashboards etc.
The shadow effect can simply be created using the JavaFX effect InnerShadow : https://docs.oracle.com/javase/8/javafx/api/javafx/scene/effect/InnerShadow.html
