### ISSUE TITLE
gradle task build is failed

### ISSUE THREAD

**Issue by ltorok** [HanSolo/Medusa#192]
Hi.
After run this command
gradlew.bat build -Dorg.gradle.java.home="C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot" I get follow output in Windows CMD console:
![image](https://user-images.githubusercontent.com/7220540/85532666-2da8f180-b610-11ea-9cc8-a0a0f6882bf3.png)
I use Gradle Wrapper (gradlew.bat, currently is used Gradle 6.4), Java is AdoptOpenJDK 11.0.7.10, OS is Windows 10.

Problem (attached screenshot):
* Where:
Build file 'D:\repositories\moje\GitHub\HanSolo\Medusa\build.gradle' line: 172

* What went wrong:
A problem occurred evaluating root project 'Medusa'.
> Could not get unknown property 'sonatypeUsername' for root project 'Medusa' of type org.gradle.api.Project.

**Comment by HanSolo** [comment]
Yep there is a problem with gradle version > 6.3 I will fix it asap.

**Comment by HanSolo** [comment]
Should be fixed with latest release

**Comment by ltorok** [comment]
Thanks. It is ok now.
