### ISSUE TITLE
How to change size of linear bar?

### ISSUE THREAD

**Issue by PAIDI-RAMESH** [HanSolo/Medusa#194]
![image](https://user-images.githubusercontent.com/61821550/87220500-ee093600-c381-11ea-910d-8c5e4c86c61a.png)
How to change customization size of the bar

**Comment by HanSolo** [comment]
The bar cannot be resized directly. The solution would be to copy the skin, make the adjustments you need to it and use it with gauge.setSkin(YOUR_CUSTOMIZED_SKIN)

**Comment by PAIDI-RAMESH** [comment]
give me any example

**Comment by PAIDI-RAMESH** [comment]
is it possible same into border
