### ISSUE TITLE
Zero not showing in scale when minvalue below zero

### ISSUE THREAD

**Issue by Higgins328** [HanSolo/Medusa#196]
Using the gauges since a few weeks back and think they are great. Found an issue thow and this is when using minvalues below zero. In this case the zero in the scale wont show, except for in the Modern skin. See screenshot below. I'm using Java 11.0.3 with OpenJFX

![zero](https://user-images.githubusercontent.com/68734993/88381982-d2515700-cda7-11ea-96ce-712eb3ea5616.PNG)

**Comment by HanSolo** [comment]
Ok...thx for reporting...will take a look at it.

**Comment by HanSolo** [comment]
Hmm...checked with the following code:
```java
gauge = GaugeBuilder.create()
                    .skinType(SkinType.MODERN)
                    .prefSize(400, 400)
                    .minValue(-50)
                    .maxValue(250)
                    .minorTickSpace(10)
                    .majorTickSpace(50)
                    .animated(true)
                    .build();
```

So you might want to provide the code you used to create the issue.


I've quickly tested with MODERN, GAUGE and DIGITAL and all of them show the "0" as you can see on the screenshots.
![Test 2020-07-24 12-31-43](https://user-images.githubusercontent.com/62843/88383063-0f1e4d80-cdaa-11ea-8b82-edb7d1af1f50.png)
![Test 2020-07-24 12-32-04](https://user-images.githubusercontent.com/62843/88383068-12193e00-cdaa-11ea-93bb-daad086a6ce8.png)
![Test 2020-07-24 12-32-24](https://user-images.githubusercontent.com/62843/88383070-12b1d480-cdaa-11ea-95ab-4ae8665f4cb3.png)

**Comment by Higgins328** [comment]
Found it! I was using .foregroundBaseColor(Color.BLACK) at same time as I use a black colored background, so the zero was there all the time but could not be seen. Changed the .foregroundBaseColor and now it all looks fine

**Comment by HanSolo** [comment]
Okidoki... 👍🏻
