### ISSUE TITLE
Missing samples / getting started

### ISSUE THREAD

**Issue by dlemmermann** [HanSolo/Medusa#2]
Would be nice to have some kind of samples / test application to get users started quickly and to highlight the libs features.

**Comment by HanSolo** [comment]
At the moment there is only the Demo.class that contains some samples and the additional Skins. I hope to find more time for creating demos and blogposts soon.

**Comment by HanSolo** [comment]
I've added 2 demos GaugeDemo and FGaugeDemo that hopefully will be helpful to understand the Medusa gauges and how to use them. You will find them in the demos package.

**Comment by HanSolo** [comment]
With the MedusaDemo project hopefully enough demos will be available
