### ISSUE TITLE
Change the fontsize of TickMarks

### ISSUE THREAD

**Issue by Pureandy** [HanSolo/Medusa#204]
Hello Gerrit,

I have a Question if it's possible to change the fontsize of Tickmarks without setting custom Tickmarks?

The Dokumentation says: The default font size is 18px at a size of 250px. This value will be used to calculate the currentfont size for the ticklabels when scaling.

The Problem is with high values as Tickmarks the numbers are going inside of the Gauge.

![Screenshot_1](https://user-images.githubusercontent.com/6490663/114357120-a5311880-9b71-11eb-8ac9-c38e6a22baa0.png)

Maybe there is an easy solution to this, that I don't see.

Thanks in advance.

**Comment by HanSolo** [comment]
If I remember right there should be a property named customTickLabelFontsize in Gauge.

**Comment by HanSolo** [comment]
Ah ok...got it...so I could implement a method that would enable custom tick label font size only e.g. setCustomTickLabelFontSizeEnabled() etc.
Would that work for you?

**Comment by Pureandy** [comment]
that would work yes :)

**Comment by HanSolo** [comment]
Ok...will implement it...and will let you know once it is in...

**Comment by HanSolo** [comment]
I've implemented it with the latest commit, could you give it a try?

**Comment by Pureandy** [comment]
I just tested it and it works. Thanks alot. 
Highly appreciate your work.
It would be very helpful if you could create a new Release with this new feature :)

**Comment by HanSolo** [comment]
Okidoki...will release a new version now...

**Comment by HanSolo** [comment]
Fixed with version 11.6
