### ISSUE TITLE
Level Gauge

### ISSUE THREAD

**Issue by sivaprashanth** [HanSolo/Medusa#205]
Can i use a level gauge with no percentages displayed and just numbers on the level gauge?

**Comment by HanSolo** [comment]
Fixed with version 11.7
You simply can set the unit to "" to get rid of the % sign

**Comment by sivaprashanth** [comment]
Can i hide the numbers and just show the level gauge and its animation

**Comment by HanSolo** [comment]
Just set the foregroundBaseColor to Color.TRANSPARENT should work

**Comment by sivaprashanth** [comment]
Thanks Hansolo that was a speedy response.

**Comment by sivaprashanth** [comment]
is that % disappearance available for java 8 versions ?
