### ISSUE TITLE
Smooth gradient precisely on gradient stop

### ISSUE THREAD

**Issue by jab27** [HanSolo/medusa#209]
The lookup of lower and upper bound precisely at a gradient stop will pick the neighbors on both sides instead of just going with the actual one. This results in interpolated color that could be quite fare off.
Example with stops defines for 0.2, 0.4, 0.6, 0.8 and 1.0 The position is 0.4 and the lower and upper bound is set to 0.2 and 0.6 in stead of just picking 0.4 for one or both. I believe the fix would be to include an equal in one or both of the compare's of method getCoulorAt(…) in tools.

public Color getColorAt(final double POSITION_OF_COLOR) {
…
if (Double.compare(fraction,POSITION) < 0) {
    lowerBound = stops.get(fraction);
}
if (Double.compare(fraction, POSITION) > 0) {
    upperBound = stops.get(fraction);
    break;
}
…

![image](https://user-images.githubusercontent.com/41075550/127054562-3436d0d0-1668-4d59-8bda-3102eb75e09a.png)

**Comment by HanSolo** [comment]
Thx for the heads up, will take a look at asap 👍🏻

**Comment by HanSolo** [comment]
Should be fixed with latest commit in jdk16 branch, could you give it a try please?

**Comment by jab27** [comment]
It's working. Thanks!
