### ISSUE TITLE
[question] java: module not found: eu.hansolo.medusa

### ISSUE THREAD

**Issue by sblantipodi** [HanSolo/medusa#210]
Hi all,
I'm trying to use the medusa gauges.

I have added those lines to my pom.xml
<dependency> <groupId>eu.hansolo</groupId> <artifactId>Medusa</artifactId> <version>16.0.0</version> </dependency>

and this to my module-info.java
requires eu.hansolo.medusa;

I can compile use mvn clean install but I cannot run my main file from intellij.
I get this error:
java: module not found: eu.hansolo.medusa

Any idea?

Thanks

**Comment by sblantipodi** [comment]
the strange thing is that if I rollback to version 11.7 it works no problem.

**Comment by HanSolo** [comment]
I needed to change the artifact id to medusa again for some ci reasons, so could you try to use: 

<dependency>
  <groupId>eu.hansolo</groupId>
  <artifactId>medusa</artifactId>
  <version>16.0.1</version>
</dependency>

That should work I hope...

**Comment by sblantipodi** [comment]
Ok it worked thanks
