### ISSUE TITLE
Issues when moving from version 11.7 to version 16.0.0

### ISSUE THREAD

**Issue by eitan-rosenberg** [HanSolo/medusa#211]
Hello,

I am trying to use version 16.0.0 and I get:

Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: G:\MyMavenRepo\eu\hansolo\Medusa\16.0.0\Medusa-16.0.0.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Package eu.hansolo.Medusa not found in module

This is my pom, and it works fine with version 11.7.
[pom.zip](https://github.com/HanSolo/medusa/files/7070337/pom.zip)

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.target>16</maven.compiler.target>
		<maven.compiler.source>16</maven.compiler.source>
	</properties>

	<dependencies>

		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-web</artifactId>
			<version>16</version>
		</dependency>

		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-swing</artifactId>
			<version>16</version>
		</dependency>

		<dependency>

			<groupId>eu.hansolo</groupId>
			<artifactId>Medusa</artifactId>
			
			<version>16.0.0</version>

			<exclusions>
				<exclusion>
					<groupId>*</groupId>
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>

		</dependency>

	</dependencies>

Any response will be welcome.

Regards.

**Comment by HanSolo** [comment]
I needed to change the artifact id to medusa so please try this:
<dependency>
  <groupId>eu.hansolo</groupId>
  <artifactId>medusa</artifactId>
  <version>16.0.1</version>
</dependency>

**Comment by eitan-rosenberg** [comment]
Hello,

That did the trick.

Thanks.
