### ISSUE TITLE
16.0.1 version not in mvnrepository

### ISSUE THREAD

**Issue by rnayabed** [HanSolo/medusa#214]
The latest version on mvnrepository is only 16.0.0 and not the latest one 

https://mvnrepository.com/artifact/eu.hansolo/Medusa/16.0.0

**Comment by HanSolo** [comment]
It was needed to change the artifact id, so you will find it here: https://mvnrepository.com/artifact/eu.hansolo/medusa/16.0.1

**Comment by rnayabed** [comment]
thank you :D
