### ISSUE TITLE
Section with negative range

### ISSUE THREAD

**Issue by mamamio723** [HanSolo/Medusa#23]
First thanks a lot for this great library! I have to create many similar gauges. So I created the following function with two section:

```java
public static Gauge create(double max)
    {
        return GaugeBuilder.create()
                .skinType(SkinType.GAUGE)
                .maxSize(150, 150)
                .minSize(150, 150)
                .title("dP")
                .unit("hPa")
                .minValue(-1.1 * max)
                .maxValue(+1.1 * max)
                .sectionsVisible(true)
                .sections(new Section(-1.1 * max, -max, Color.LIGHTCORAL),
                        new Section(+max, +1.1 * max, Color.LIGHTCORAL))
                .build();
    }
```
With

```java
create(20d);
```
I get

![medusa1](https://cloud.githubusercontent.com/assets/18207637/14200938/d6f66e3c-f7ee-11e5-9089-0e92999aaaa6.png)

To start the section at -25 and stop at +25 I tried to increase the section range (note the -25 and +25 range is computed by the Medusa library):

```java
                .sections(new Section(-2 * max, -max, Color.LIGHTCORAL),
                        new Section(+max, +2 * max, Color.LIGHTCORAL))
```
While this works for the section on the right side, the section on the left side does not draw correctly.

![medusa2](https://cloud.githubusercontent.com/assets/18207637/14200942/dcfef88a-f7ee-11e5-8352-2161fe47b4e9.png)

**Comment by HanSolo** [comment]
Fixed with latest commit
