### ISSUE TITLE
Tick label text incorrect

### ISSUE THREAD

**Issue by mamamio723** [HanSolo/Medusa#24]
For small ranges the tick labels are drawn incorrect:

The following code
```java
GaugeBuilder.create()
                .skinType(SkinType.GAUGE)
                .maxSize(200, 200)
                .minSize(200, 200)
                .title("dP")
                .unit("hPa")
                .minValue(-2.2)
                .maxValue(+2.2)
                .build();
```
creates the following gauge:
![medusa3](https://cloud.githubusercontent.com/assets/18207637/14201160/58839190-f7f0-11e5-9476-a173fdd9ed5a.png)

The tick labels are [0, 1, 1, 2, 2, 3] instead of [0, 0.5, 1, 1.5, 2, 2.5]. Probably it is even better to label only integer numbers like [0, 1, 2].

Thanks!

**Comment by HanSolo** [comment]
If you set ticklabelDecimals to e.g. 1 you will see that they are correct (hopefully) :)
