### ISSUE TITLE
Can't change min/max value at runtime

### ISSUE THREAD

**Issue by OmriSoudry** [HanSolo/Medusa#26]
I need to change the min/max values of my gauge according to the user's selection, but when I call "setMin[or max]Value" after the user has selected an option, I get a StackOverflow error.

The gauge is initialized in the FXML file.

**Comment by HanSolo** [comment]
Could you provide some code to reproduce the problem?

**Comment by HanSolo** [comment]
I've tried to reproduce with the attached code but for me it seems to work, so please provide some sample code so that I can help you.
[src.zip](https://github.com/HanSolo/Medusa/files/338646/src.zip)
