### ISSUE TITLE
LinearSkin drawing outside its boundaries

### ISSUE THREAD

**Issue by MichalHe** [HanSolo/Medusa#28]
LinearSkin gauge has no problem drawing the gauge outside its boundaries, when using `Orientation.HORIZONTAL` on `LinearSkin`.
My opinion is that the issue is caused by calculating height of canvas from width of the `Gauge`

Note: `Orientation.VERTICAL` gauges working fine

**Comment by HanSolo** [comment]
Can you provide a code snippet that shows the effect?

**Comment by MichalHe** [comment]
Sorry that it took me so long
Just remove the package line.

[code.zip](https://github.com/HanSolo/Medusa/files/360990/code.zip)

**Comment by HanSolo** [comment]
Fixed in release 5.3
