### ISSUE TITLE
BulletChartSkin not rendering title?

### ISSUE THREAD

**Issue by MichalHe** [HanSolo/Medusa#29]
Sorry for creating another issue, maybe it's my mistake
Following code is not rendering title:
        `gauge3 = GaugeBuilder.create()
                .barBorderColor(Color.WHITE)
                .needleBorderColor(Color.WHITE)
                .borderWidth(2)
                .borderPaint(Color.WHITE)
                .barColor(Color.AZURE)
                .titleColor(Color.WHITE)
                .subTitleColor(Color.WHITE)
                .unitColor(Color.WHITE)
                .majorTickMarkColor(Color.WHITE)
                .tickLabelColor(Color.WHITE)
                .valueColor(Color.WHITE)
                .build();`
        `gauge3.setSkin(new BulletChartSkin(gauge3));`
        `gauge3.setTitle("TITLE");`
        `gauge3.setTitleColor(Color.WHITE);`
        `gauge3.setValue(10);`

![example](https://cloud.githubusercontent.com/assets/10884550/16801078/f731939c-48f8-11e6-90c1-5443111a2664.PNG)

**Comment by HanSolo** [comment]
The problem is you first instantiate a gauge object and afterwards you set the Skin. It's way better to use the GaugeBuilder to do that, so instead of using 
```java
gauge3.setSkin(new BulletChartSkin(gauge3)) 
```
you should use it as follows:
```java
gauge = GaugeBuilder.create()
                    .skinType(SkinType.BULLET_CHART) // <---
                    .barBorderColor(Color.WHITE)
                    .needleBorderColor(Color.WHITE)
                    .borderWidth(2)
                    .borderPaint(Color.WHITE)
                    .barColor(Color.AZURE)
                    .foregroundBaseColor(Color.WHITE)
                    .thresholdColor(Color.WHITE)
                    .title("TITLE")
                    .threshold(75)
                    .value(10)
                    .build();
```
But nevertheless the BulletChartSkin had the same problem as the LinearSkin, so I fixed it with the last commit :)
