### ISSUE TITLE
Gauges not redrawing when window resize

### ISSUE THREAD

**Issue by MichalHe** [HanSolo/Medusa#30]
This issue can be reproduced by using the code I sent you yesterday.
Just set the `CustomPanel ` as center to scene and then maximize window - gauges won't redraw.
Then minimize the window - gauges will be drawn with the scale as they're in the maximized window.

Note: This seems only to be affecting LinearSkin (maybe BulletChartSkin too), other gauges will redraw.
Note: Using medusa-5.3

PS> sorry for another issue

**Comment by MichalHe** [comment]
Also try setting values to gauges and then resize

**Comment by HanSolo** [comment]
Hmm...strange...I can't reproduce this one on OS X. I see the problem with the drawing outside it's bounds which seems to be related to the FullScreen Mode switch and I will try to fix this but I can't see the effect you described. Ideas?
Oh and btw don't worry about new issues...I'm happy to fix everything you'll find :)

**Comment by MichalHe** [comment]
Sending you screenshots
I was able to reproduce this on 2 PCs, both running Windows (8.1 & 7)
Issue persists even if I run this in `JFXPanel`

medusa_bug1 is when the window has full size
medusa_bug2 is when it's resized back from full screen - seems to draw gauges scaled to the max window

**Comment by MichalHe** [comment]
will test right now

**Comment by HanSolo** [comment]
Made further tests and release 5.5 seems to fix this problem...I hope ;)

**Comment by MichalHe** [comment]
Can confirm that the commit fixed both problems, BTW thanks for this awesome lib

**Comment by HanSolo** [comment]
Awesome...thanks a lot for testing... :)
