### ISSUE TITLE
Getting bar bounds (LinearSkin) for custom event listener

### ISSUE THREAD

**Issue by MichalHe** [HanSolo/Medusa#32]
Is there a way to get bar bounds when using `LinearSkin` for custom event listener?

**Comment by HanSolo** [comment]
Nope there is currently no way to do that. Because I have to implement it in the main model which is used by all gauges I would only do that if it really makes sense for other skins too.
What do you plan to do with the event?

**Comment by MichalHe** [comment]
set Value of gauge by x coords

**Comment by HanSolo** [comment]
So you mean moving the bar by mouse?

**Comment by MichalHe** [comment]
exactly my plan, 
I have already written simmilar function for normal non-linear gauges, where the knob is in the center.

**Comment by HanSolo** [comment]
ok...let me think about that...

**Comment by HanSolo** [comment]
I thought about it but this seems to be more a non standard use-case which means my advice would be to fork the LinearSkin and create your own skin that does what you need. To me it does not make sense to add that functionality to the default LinearSkin...sorry :)
