### ISSUE TITLE
`LinearSkin` shows max value 160 instead of 150

### ISSUE THREAD

**Issue by MichalHe** [HanSolo/Medusa#33]
`LinearSkin` shows max value 160 instead of 150.
I assume the library is calculating this number for proper drawing of the scale.
How can this be avoided?

**Comment by HanSolo** [comment]
You can set autoscale to false then it should take the values you defined for min and max value. You can also define major and minor tickspacing but I did not spend much time to optimize the non-autoscale mode.

**Comment by MichalHe** [comment]
autoScale off with the example I sent you creates java process that takes cca 970 MB ram (LoL)
however no errors are reported
