### ISSUE TITLE
Redraw gauge after changing section start/end

### ISSUE THREAD

**Issue by MichalHe** [HanSolo/Medusa#34]
When using `gauge.getSection().get(0).setStart()` -> won't redraw until I redraw (resize) it manually
Adding change listeners to section start/end property should fix this issue, however I assume that Section doesn't have internal reference to parent gauge, so this is probably behavior needs to be implemented by changing(appending) to function addSection where for every Section needs to be done something like this `section.startProperty.addListener(<redraw>)`

**Comment by HanSolo** [comment]
The idea is not to change sections on the fly. I would like to avoid adding listeners to each section but I'll make some tests next week.

**Comment by MichalHe** [comment]
No problem, I can solve this myself (the ugly way, but works)

**Comment by HanSolo** [comment]
Sections will now fire an event of type SectionEvent.SECTION_UPDATE whenever a property changed. You can trigger a redraw of the gauge by using the following line
```java
gauge.getSections().forEach(section -> section.setOnSectionUpdate(sectionEvent -> gauge.fireUpdateEvent(new UpdateEvent(YOUR_APP_CLASS.this, EventType.REDRAW))));
```
I hope that will help you to avoid "ugly" code ;)
