### ISSUE TITLE
Gauge not redrawing with update event

### ISSUE THREAD

**Issue by MichalHe** [HanSolo/Medusa#38]
```
 configurationGauge.getSections().forEach(section -> section.setOnSectionUpdate(sectionEvent ->{
                System.out.println("Updating section");
                configurationGauge.fireUpdateEvent(new UpdateEvent(ConfigGaugeWindow.this, UpdateEvent.EventType.REDRAW));
        }));
```
Following code is printing to console, however it's not redrawing the Gauge (Am I doing something wrong?) 
The gauge is in Gauge --> BorderPane --> GridPane --> GaugeConfigWindow

**Comment by HanSolo** [comment]
You are right...there was some code missing in the LinearSkin redraw() method. Will be fixed with next release (after my vacation) :)

**Comment by MichalHe** [comment]
Enjoy :sunglasses:
