### ISSUE TITLE
Suggestion: 'Bundle-SymbolicName' : 'eu.hansolo.medusa'

### ISSUE THREAD

**Issue by claudio-rosati** [HanSolo/Medusa#44]
In build.gradde add `'Bundle-SymbolicName' : 'eu.hansolo.medusa'` to jar manifest attributes, thus avoiding it being set by default to `'Medusa'`.

Regards,
Claudio

**Comment by HanSolo** [comment]
Will come with version 6.1

**Comment by claudio-rosati** [comment]
Have you an idea about when 6.1 will be released?
Thank you,
Claudio

**Comment by HanSolo** [comment]
Maybe I'll implement the new average feature in more skins first before I'll release 6.1...but it might be within the next week...
