### ISSUE TITLE
Medusa 6.4

### ISSUE THREAD

**Issue by claudio-rosati** [HanSolo/Medusa#45]
Hello,

I cannot find it on maven central. Have you deployed there?

Regards,
Claudio

**Comment by wimdeblauwe** [comment]
Seems to be there: https://mvnrepository.com/artifact/eu.hansolo/Medusa/6.4

**Comment by claudio-rosati** [comment]
Yes I've seen it.
It seems that when you announce a new version, maven central need a bit of time before showing the artifact.
Thank you,
Claudio
