### ISSUE TITLE
LcdClockSkin width incorrect

### ISSUE THREAD

**Issue by wimdeblauwe** [HanSolo/Medusa#50]
If you run this program:

```
import eu.hansolo.medusa.Clock;
import eu.hansolo.medusa.ClockBuilder;
import eu.hansolo.medusa.LcdDesign;
import eu.hansolo.medusa.LcdFont;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundFill;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.paint.Color;
import javafx.stage.Stage;

public class LcdClockSkinTest extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        BorderPane root = new BorderPane();
        HBox topPanel = new HBox();
        topPanel.setBackground(new Background(new BackgroundFill(Color.BLACK, null, null)));
        topPanel.setMaxHeight(50);
        topPanel.setAlignment(Pos.CENTER_RIGHT);
        Clock clock = createClock();
        topPanel.getChildren().add(clock);
        root.setTop(topPanel);
        Scene scene = new Scene(root);
        scene.widthProperty().addListener((observableValue, oldValue, newValue) -> {
            System.out.println( "scene: " + newValue );
            System.out.println( "clock: " + clock.getWidth());
        });
        primaryStage.setScene(scene);
        primaryStage.setWidth(800);
        primaryStage.setHeight(600);
        primaryStage.show();
    }

    private Clock createClock() {
        Clock clock = ClockBuilder.create()
                                  .skinType(Clock.ClockSkinType.LCD)
                                  .lcdDesign(LcdDesign.BLUE)
                                  .lcdFont(LcdFont.DIGITAL)
                                  .lcdCrystalEnabled(true)
                                  .dateVisible(false)
                                  .secondsVisible(true)
                                  .build();
        clock.setRunning(true);
        clock.setBackground(new Background(new BackgroundFill(Color.YELLOW, null, null)));
        clock.setOnMouseClicked(event -> Platform.exit());
        return clock;
    }
}
```

It will give the following result:
![image](https://cloud.githubusercontent.com/assets/1115823/21350024/7cdb373e-c6b5-11e6-8f9f-1dfc44d1b7b5.png)

Notice how the yellow rectangle is the background of the clock. I would like to be able to have the clock to the far right in the top bar, but the clock node itself takes more width then it is actually using when drawing.

This is tested with version 6.8 and the current master (dd627efce0483a8213debebecaeb3f7d15ee8e2a)

**Comment by HanSolo** [comment]
Well the problem is keeping the aspect ratio of the clock leads to exactly this effect. At the moment I don't have a good solution to overcome this problem but you could set the maxWidth of the clock by using the following formular which should at least help you here:
clock.setMaxWidth(HEIGHT / 0.52631579)
HEIGHT is your max height (50 in your example)

**Comment by wimdeblauwe** [comment]
Thanks for the workaround for now. I just tried it and it works.

One thing to look out for: I noticed when I added padding at the bottom and the top, I have to subtract that from the height to make it work.

So without padding, I did `.maxWidth( 50 / 0.52631579)` and it was nicely right aligned. With the padding, I need to do:

    .maxWidth(40 / 0.52631579)
    .padding(new Insets(5, 0, 5, 0))

to keep the clock on the right edge. (With the 40 being the original height of 50 minus 2 times 5 pixels padding).

**Comment by wimdeblauwe** [comment]
One more question @HanSolo : Is the number I need to use the same for the lcd gauge?

**Comment by HanSolo** [comment]
Nope, for the LCD gauge skin you will need: 0.45454545

**Comment by HanSolo** [comment]
Just don't have the time at the moment to take a closer look which is the reason for not fixing it...So it's not forgotten.
