### ISSUE TITLE
How to remove the alert icon in the LCD gauge?

### ISSUE THREAD

**Issue by wimdeblauwe** [HanSolo/Medusa#51]
I am using the LCD gauge, but I have not found in the docs how to remove the alert icon:

![image](https://cloud.githubusercontent.com/assets/1115823/21366512/64c7c7d0-c6fa-11e6-9bc0-b7a4b4e2d8b8.png)

I thought it was `thresholdVisible`, but does not seem to be it.

**Comment by HanSolo** [comment]
Fixed the bug with latest commit
