### ISSUE TITLE
gauge.areasVisibleProperty appears to have no effect after gauge has been drawn

### ISSUE THREAD

**Issue by digitig** [HanSolo/Medusa#53]
Changing the areasVisibleProperty after the gauge has been drawn does not appear to have any effect on the visibility of areas.

_CheckBox areasVisibleBox = new CheckBox();
//...
areasVisibleBox.selectedProperty().bindBidirectional(gauge.areasVisibleProperty());_

The checkbox correctly reflects the initial state of areasVisibleProperty (set by the builder), but changing it does not change the visibility of areas.

**Comment by HanSolo** [comment]
You are absolutely right, just saw the problem, will fix it tomorrow morning :)

**Comment by HanSolo** [comment]
Fixed :)
