### ISSUE TITLE
Max value of gauge not matching what is specified

### ISSUE THREAD

**Issue by mcarlin** [HanSolo/Medusa#55]
I've run into an issue where when I specify the max value of the gauge what is displayed doesn't match what I specified. In the following case it doesn't match (I set 3600 but it displays 4000):

Gauge gauge = GaugeBuilder.create()
                                  .skinType(Gauge.SkinType.DASHBOARD)
                                  .minValue(0)
                                  .maxValue(3600)
                                  .animated(true)
                                  .valueVisible(false)
                                  .build();

I'm using Medusa 7.3 and java 1.8u60

**Comment by mcarlin** [comment]
Here's a sample that exhibits the behavior:

```
import eu.hansolo.medusa.Gauge;
import eu.hansolo.medusa.GaugeBuilder;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class GaugeIssue extends Application{
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        Gauge gauge = GaugeBuilder.create()
                .skinType(Gauge.SkinType.DASHBOARD)
                .minValue(0)
                .maxValue(3600)
                .animated(true)
                .valueVisible(false)
                .build();

        StackPane root = new StackPane();
        root.getChildren().add(gauge);
        primaryStage.setScene(new Scene(root, 300, 250));
        primaryStage.show();
    }
}
```

**Comment by HanSolo** [comment]
Well the reason for this is the autoscaling of the gauge. This was implemented to achieve nice scales. To disable this feature you might want to use setAutoscaling(false).
