### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by claudio-rosati** [HanSolo/Medusa#56]
Hello,

I run the following simple code and when, after 5 seconds, the skin is changed a NullPointer happens. What is wrong in my code?

```java
package se.ess.medusa.tests.clock;


import eu.hansolo.medusa.Clock;
import eu.hansolo.medusa.ClockBuilder;
import java.util.logging.Logger;
import javafx.animation.AnimationTimer;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.NodeOrientation;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.scene.paint.Color;
import javafx.stage.Stage;

import static javafx.application.Application.launch;


public class MainApp extends Application {

    private static final Logger LOGGER = Logger.getLogger(MainApp.class.getName());

    public static void main( String[] args ) {
        launch(args);
    }

    private Clock clock;
    private long lastTimerCall;
    private AnimationTimer timer;

    @Override
    public void init() throws Exception {

        clock = ClockBuilder.create()
                            .skinType(Clock.ClockSkinType.PLAIN)
                            .backgroundPaint(Color.web("#1f1e23"))
                            .borderPaint(Color.web("#03af07"))
                            .borderWidth(8.5)
                            .running(true)
                            .build();

        lastTimerCall = System.nanoTime();
        timer = new AnimationTimer() {
            @Override
            public void handle( long now ) {
                if ( now > lastTimerCall + 5_000_000_000L ) {

                    clock.setSkinType(Clock.ClockSkinType.SLIM);

                    lastTimerCall = now;

                }
            }
        };

    }
    
    @Override
    public void start( Stage stage ) throws Exception {

        StackPane pane = new StackPane(clock);

        pane.setPadding(new Insets(20));
        pane.setNodeOrientation(NodeOrientation.LEFT_TO_RIGHT);

        Scene scene = new Scene(pane);

        stage.setTitle("Medusa Clock Test");
        stage.setScene(scene);
        stage.show();

        timer.start();

    }

}
```

**Comment by HanSolo** [comment]
hmm...what is the reason for setting the skin at runtime?

**Comment by claudio-rosati** [comment]
I'm the responsible at the Auropean Spallation Source ERIC of the software used to control the proton accelerator.

The software currently used is called Control System Studio and already has a tool to design OPIs (operator interfaces), but I'm working to a new version based on JavaFX (run from inside an Eclipse-based container).

The OPI a designed draggning widgets into and editor and then configuring it changing properties.

When the OPI is designed can be used in production by a specific engine that loads and displays it.

During the design phase I need users be able to alter properties to suit their needs. The skin is one of the properties (probably the most important).

Currently I'm working with clock, being the simplest widget I need to implement (allowing me to practice with Medusa), then will move to gauges.

**Comment by HanSolo** [comment]
Ah...ok, makes sense. Well I'm currently looking into this but usually that should not be a problem because it also works in SceneBuilder which does in principle the same. Will further investigate, please let me know if you run in more problems.

**Comment by claudio-rosati** [comment]
I'll do.
Thank you

**Comment by HanSolo** [comment]
Ok, I've found the problem...I do not really unregister existing listeners which leads to the problem...means I have to implement a proper dispose method in all skins.

**Comment by claudio-rosati** [comment]
OK. 
I'll wait for the fix.
Thank you.

**Comment by HanSolo** [comment]
I've fixed some clock skins already but I will also have to fix all the gauge skins and the rest of the clock skins...so it might take some days to finalize it :)

**Comment by claudio-rosati** [comment]
OK, thank you.

**Comment by HanSolo** [comment]
fixed with release 7.5 ...hopefully ;)

**Comment by claudio-rosati** [comment]
Thank you so much.

**Comment by HanSolo** [comment]
My pleasure :)

**Comment by claudio-rosati** [comment]
Have you plublished 7.5 on Maven Central (I cannot see it yet)?

**Comment by HanSolo** [comment]
Yep but it could take some time until it will appear. You might want to use the binary from bintray.
