### ISSUE TITLE
Problems selecting and resizing FGauge

### ISSUE THREAD

**Issue by claudio-rosati** [HanSolo/Medusa#58]
If I use a Gauge I can click on it and resize works very well.

The following code displays in console a message when the component is clicked. Moreover, resizing the window will always display the component centered.

```java
package se.ess.medusa.tests.gauge;

import eu.hansolo.medusa.Gauge;
import eu.hansolo.medusa.GaugeBuilder;
import eu.hansolo.medusa.GaugeDesign;
import java.util.logging.Logger;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.NodeOrientation;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import static javafx.application.Application.launch;

public class MainApp extends Application {

    private static final Logger LOGGER = Logger.getLogger(MainApp.class.getName());

    public static void main( String[] args ) {
        launch(args);
    }

    private Gauge gauge;

    @Override
    public void init() throws Exception {

        GaugeDesign design = GaugeDesign.NONE;
        Gauge.SkinType skin = Gauge.SkinType.SIMPLE_SECTION;

        gauge = GaugeBuilder.create()
                            .skinType(skin)
                            .title(skin.name() + " - " + design.name())
                            .build();

    }

    @Override
    public void start( Stage stage ) throws Exception {

        final Node node = gauge;

        node.addEventHandler(MouseEvent.MOUSE_PRESSED, e -> System.out.println("*** SELECTED"));

        StackPane pane = new StackPane(node);

        pane.setPadding(new Insets(20));
        pane.setNodeOrientation(NodeOrientation.LEFT_TO_RIGHT);

        Scene scene = new Scene(pane);

        stage.setTitle("Medusa Clock Test");
        stage.setScene(scene);
        stage.show();

        timer.start();

    }

}
```

If, instead, I use an FGauge then

- I cannot anymore click on the component,
- Resizing is strange, being also X and Y affected.

Here the code. As you can see:

- Clicking the component will not display a message on the console;
- If you drag the right edge of the window, often the component is no more perfectly centered.

```java
package se.ess.medusa.tests.gauge;

import eu.hansolo.medusa.FGauge;
import eu.hansolo.medusa.FGaugeBuilder;
import eu.hansolo.medusa.Gauge;
import eu.hansolo.medusa.GaugeBuilder;
import eu.hansolo.medusa.GaugeDesign;
import java.util.logging.Logger;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.NodeOrientation;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import static javafx.application.Application.launch;

public class MainApp extends Application {

    private static final Logger LOGGER = Logger.getLogger(MainApp.class.getName());

    public static void main( String[] args ) {
        launch(args);
    }

    private Gauge gauge;

    @Override
    public void init() throws Exception {

        GaugeDesign design = GaugeDesign.NONE;
        Gauge.SkinType skin = Gauge.SkinType.SIMPLE_SECTION;

        gauge = GaugeBuilder.create()
                            .skinType(skin)
                            .title(skin.name() + " - " + design.name())
                            .build();

        fgauge = FGaugeBuilder.create()
                              .gauge(gauge)
                              .gaugeDesign(design)
                              .build();

    }

    @Override
    public void start( Stage stage ) throws Exception {

        final Node node = fgauge;

        node.addEventHandler(MouseEvent.MOUSE_PRESSED, e -> System.out.println("*** SELECTED"));

        StackPane pane = new StackPane(node);

        pane.setPadding(new Insets(20));
        pane.setNodeOrientation(NodeOrientation.LEFT_TO_RIGHT);

        Scene scene = new Scene(pane);

        stage.setTitle("Medusa Clock Test");
        stage.setScene(scene);
        stage.show();

        timer.start();

    }

}
```

**Comment by HanSolo** [comment]
Well the FGauge is more or less a special wrapper around a Gauge. So you should not use a styled gauge like you did but more like in the following example.

`import java.util.logging.Logger;

import eu.hansolo.medusa.Gauge.SkinType;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.NodeOrientation;
import javafx.scene.Scene;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;


public class MainApp extends Application {

    private static final Logger LOGGER = Logger.getLogger(MainApp.class.getName());

    public static void main( String[] args ) {
        launch(args);
    }

    private Gauge gauge;
    private FGauge fgauge;

    @Override public void init() throws Exception {

        GaugeDesign design = GaugeDesign.NONE;
        SkinType    skin   = Gauge.SkinType.SIMPLE_SECTION;

        gauge = GaugeBuilder.create().build();
        gauge.setMouseTransparent(true);

        fgauge = FGaugeBuilder.create()
                              .gauge(gauge)
                              .build();

        fgauge.addEventHandler(MouseEvent.MOUSE_PRESSED, e -> System.out.println("*** SELECTED"));
    }

    @Override public void start( Stage stage ) throws Exception {

        StackPane pane = new StackPane(fgauge);

        pane.setPadding(new Insets(20));
        pane.setNodeOrientation(NodeOrientation.LEFT_TO_RIGHT);

        Scene scene = new Scene(pane);

        stage.setTitle("Medusa Clock Test");
        stage.setScene(scene);
        stage.show();
    }
}
`

**Comment by claudio-rosati** [comment]
Thank you for the `gauge.setMouseTransparent(true);` hint.

Have you seen the resize problem?

**Comment by HanSolo** [comment]
I sometimes see that the gauge is not aligned correctly which seems to be the case if I resize too fast. The whole FGauge control is more to show the possibility of using borders to create some kind of frame around a Gauge control. I would suggest not to use it in the current state. To be honest I was thinking about to remove the FGauge from the lib.

**Comment by claudio-rosati** [comment]
OK, I'll not use it.
Thank you
