### ISSUE TITLE
Wrong default settings when using QuarterSkin

### ISSUE THREAD

**Issue by dlemmermann** [HanSolo/Medusa#6]
When just setting the skin the other default settings do not work. See screenshot.

![bildschirmfoto 2016-01-18 um 13 01 26](https://cloud.githubusercontent.com/assets/9534301/12390841/b805ec2c-bde3-11e5-9c42-8b9852249d05.png)

To reproduce:

        gauge1 = GaugeBuilder.create()
                             .skin(QuarterSkin.class)
                             .build();

**Comment by HanSolo** [comment]
Looks like you modified the OverviewDemo where the the gauge1 will later be used in a FGauge control. This FGauge will now throw a RuntimeException when you try to apply it to a Gauge that has a Skin different than the GaugeSkin.
If you simply use it the way you showed, it will work :)
