### ISSUE TITLE
Changing Locale at runtime to a Clock will not update the date.

### ISSUE THREAD

**Issue by claudio-rosati** [HanSolo/Medusa#60]
Changing Locale at runtime to a Clock will not update the date.
If you try with Clock.ClockSkinType.TEXT changing from Locale.US to Locale.ITALY will see the time changing format, but not the date. All other skins have the same problem with the date.

**Comment by claudio-rosati** [comment]
Clock.ClockSkinType.LCD seems being the only one working.

**Comment by HanSolo** [comment]
Yep, that's correct, not every skin implements every feature.
