### ISSUE TITLE
How "highlight sections" is supposed to work?

### ISSUE THREAD

**Issue by claudio-rosati** [HanSolo/Medusa#63]
Hello,

that one is not a bug (I believe), just a question: I don't understand how "highlight sections" is supposed to work.

I've set it to true and false but I've not seen any difference.

Can you please give me an example?

Thank you,
Claudio

**Comment by HanSolo** [comment]
The highlight sections property is not implemented in all skins. The idea is to highlight the section that contains the current value. You could see it in action in the medusa demo project [medusademo](https://github.com/HanSolo/medusademol)

**Comment by claudio-rosati** [comment]
Thank you
