### ISSUE TITLE
Feature Request: meters adjustement

### ISSUE THREAD

**Issue by claudio-rosati** [HanSolo/Medusa#65]
Hello,

in my application at ESS I've decided to group Medusa Gauge instances in 2 categories: meters and gauges.

Meters will use the following skin: AMP, GAUGE, HORIZONTAL, LINEAR, QUARTER, VERTICAL and THREE-QUARTERS (creates from OverviewDemo's gauge9).

![meters](https://cloud.githubusercontent.com/assets/10833922/22427190/75b7de22-e702-11e6-9ccc-900a8891f81e.png)

All these sking have a lot of common characteristics, but few are missing:

- AMP and LINEAR don't have sections highligh, markers and threshold;
- VERTICAL doesn't have LCD support.

Moreover, the LED inside GAUGE, HORIZONTAL, QUARTER and VERTICAL is small and, due to its position, can be hidden by the needle. So my suggestion is a bigger led positioned on the top-left angle, like in AMP.

**Comment by claudio-rosati** [comment]
Would also be good having a THREE-QUARTERS skin ;-)

**Comment by HanSolo** [comment]
If I understand you right this should be possible by using the GaugeSkin and set the angleRange to 270 degrees :)

**Comment by HanSolo** [comment]
the AMP skin was more or less another test (like the FGauge). In principle the idea is not to provide solutions for all problems but give users examples on how to create their own skins. So you could for example take the LinearSkin, fork it and tweak it in the way you like. After that you could use your own skin by calling setSkin(myOwnSkin) on the gauge control :)
You are right, the Led size and locations are not optimal but I don't like the idea to put them somewhere "outside" the gauge , I'll increase them a bit and try to find better locations :)

**Comment by claudio-rosati** [comment]
> the AMP skin was more or less another test

I agree. I think I'll not give AMP to my users: it is easy to put a coubple of rounded rectangle below an HORIZONTAL to obtain the same thing.

> take the LinearSkin, fork it and tweak it in the way you like

OK, I'll do it to enable the same "sections highligh" behavior the is the one I'm more interested in now.

> I don't like the idea to put them somewhere "outside" the gauge

OK, probably it could be on the right side of the knob for GAUGE and HORIZONTAL, over the knob for QUARTER and VERTICAL.

**Comment by HanSolo** [comment]
So I've increased the size of the LED in the given skins and I think I will stay with the current LED positions. If you really need another indication you might want to use an addition control (e.g. I could send you the LED as stand alone control) and add it to your dashboard where ever you need it. I think this would make more sense than modifying the skins until they will fit your current needs.
It's pretty easy to link an external control to the thresholdExceeded property from the outside. I hope this is ok for you...

**Comment by claudio-rosati** [comment]
OK, thank you.
I remember to have read your article about LED, by I'm unable to find it now.
If you can send me the LED stand alone control or the link to the artile will be much appreciated.

**Comment by HanSolo** [comment]
You should find different implementations of the LED control here: https://github.com/HanSolo/hol1634/tree/master/src/main/java/eu/hansolo/fx/hol1634/regionbased
