### ISSUE TITLE
DashboardSkin does not work if min value is greater than 0

### ISSUE THREAD

**Issue by adrianromero** [HanSolo/Medusa#7]
Setting min value to a value greater than 0 with DashboardSkin does not work properly. It fills the whole semicircle of the gauge.

To reproduce it just add to OverviewDemo.java, in line 206  the following: 

    .minValue(15)

And execute the demo

**Comment by HanSolo** [comment]
Problem is fixed with latest commit and was also present in IndicatorSkin and KpiSkin.
