### ISSUE TITLE
Last changes on maven

### ISSUE THREAD

**Issue by claudio-rosati** [HanSolo/Medusa#72]
Hello Gerrit,

is it posible to have the last changes/merges put on Maven central?

Thank you,
Claudio

**Comment by HanSolo** [comment]
Hi Claudio,

Sure, I was just not sure if there will be more pull requests coming :)
Will do a release later today and publish it to maven central (might take a day or two to appear).

Cheers,
Gerrit

**Comment by claudio-rosati** [comment]
Thank you
