### ISSUE TITLE
Problem with display Meduse

### ISSUE THREAD

**Issue by tomaszbaggit** [HanSolo/Medusa#93]
Hello 

I dont know do I can write here but i have problem with simple display Meduse. I want display simplest demo Medusa but my code dont show anything in IntelliJ only 
{"title":"Title","subTitle":"Title","unit":"Unit","value":0.0,"minValue":0.0,"maxValue":100.0,"threshold":100.0,"minMeasuredValue":100.0,"maxMeasuredValue":0.0}
will you help me? :)

**Comment by HanSolo** [comment]
Could you provide the code you try to run? With the given information I can't reproduce your problem.
Thanx,
Gerrit

**Comment by tomaszbaggit** [comment]
Yes of course. Maybe I made some fundamental error in the code because I just started with Scene Builder and JavaFX and general Java.

I can create simple JavaFX window with button and Label. We click Button and Label shows some text.
Finally I want display some data from MySQL but I have problem with simply Gauge


```
package sample;

import eu.hansolo.medusa.Gauge;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class Main extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception{
        Parent root = FXMLLoader.load(getClass().getResource("sample.fxml"));
        primaryStage.setTitle("Hello World");
        primaryStage.setScene(new Scene(root, 300, 275));
         Gauge wykres = new Gauge();
        primaryStage.show();
    }


    public static void main(String[] args) {
        launch(args);
    }
}
```

and Controller.java
```
package sample;

import eu.hansolo.medusa.Gauge;
import eu.hansolo.medusa.GaugeBuilder;

public class Controller {

    public void Wykres(){
        try {

            Gauge gauge = GaugeBuilder.create()
                    .title("Title")
                    .subTitle("SubTitle")
                    .unit("Unit")
                    .build();
                    System.out.println("Done"); // I print this to check do void Wykres was launched




        }catch (Exception ex){
            System.out.println("Error: " + ex);
        }
    }
}
```

```
<?xml version="1.0" encoding="UTF-8"?>

<?import javafx.scene.control.Button?>
<?import javafx.scene.control.Label?>
<?import javafx.scene.layout.Pane?>

<Pane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="400.0" prefWidth="600.0" xmlns="http://javafx.com/javafx/8.0.111" xmlns:fx="http://javafx.com/fxml/1" fx:controller="sample.Controller">
   <children>
      <Label fx:id="label1" layoutX="73.0" layoutY="62.0" prefHeight="299.0" prefWidth="423.0" />
      <Button fx:id="btn" layoutX="14.0" layoutY="21.0" mnemonicParsing="false" onAction="#Wykres" text="Button" />
   </children>
</Pane>

```

**Comment by HanSolo** [comment]
You have several problems in your code, first of all you never add the gauge to the panel which is the reason why you don't see anything :)
Secondly your Controller should implement Initializable. And third you maybe better add the Medusa.jar to SceneBuilder which enables you to directly use the Gauges within SceneBuilder (which might be better approach when using FXML).
I've added a FXMLDemo in the [medusademo](https://github.com/HanSolo/medusademo) project, please take a look there to see how it works.
Cheers,
Gerrit

**Comment by tomaszbaggit** [comment]
Thank you very much for your answer i opened "CompasGauge"

I understand that I should open this demo files in Java IntelliJ or
IntelliJ JavaFX project :)

of course I should include libs like:
gradle-wrapper file . jar
Medusa-7.4.jar
regulators-1.6.2.jar
tilesfx.jar



2017-02-20 16:37 GMT+01:00 Gerrit Grunwald <notifications@github.com>:

**Comment by tomaszbaggit** [comment]
Why I asking because after open demo file in IDEA and add libs I cant run
program = green Arrow is black :/

For beginers always wind are in eyes :)

20 lut 2017 18:05 "Tomasz Bagiński" <tomaszbag@gmail.com> napisał(a):
